/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReportID = IDL.Nat;
export const ReportStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'underReview' : IDL.Null,
  'rejected' : IDL.Null,
});
export const CyberbullyingReport = IDL.Record({
  'id' : ReportID,
  'status' : ReportStatus,
  'isAnonymous' : IDL.Bool,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'reporter' : IDL.Principal,
});

export const idlService = IDL.Service({
  'getAllReports' : IDL.Func([], [IDL.Vec(CyberbullyingReport)], ['query']),
  'getReport' : IDL.Func([ReportID], [CyberbullyingReport], ['query']),
  'getReportsByStatus' : IDL.Func(
      [ReportStatus],
      [IDL.Vec(CyberbullyingReport)],
      ['query'],
    ),
  'submitReport' : IDL.Func([IDL.Text, IDL.Bool], [ReportID], []),
  'updateReportStatus' : IDL.Func([ReportID, ReportStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReportID = IDL.Nat;
  const ReportStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'underReview' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const CyberbullyingReport = IDL.Record({
    'id' : ReportID,
    'status' : ReportStatus,
    'isAnonymous' : IDL.Bool,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'reporter' : IDL.Principal,
  });
  
  return IDL.Service({
    'getAllReports' : IDL.Func([], [IDL.Vec(CyberbullyingReport)], ['query']),
    'getReport' : IDL.Func([ReportID], [CyberbullyingReport], ['query']),
    'getReportsByStatus' : IDL.Func(
        [ReportStatus],
        [IDL.Vec(CyberbullyingReport)],
        ['query'],
      ),
    'submitReport' : IDL.Func([IDL.Text, IDL.Bool], [ReportID], []),
    'updateReportStatus' : IDL.Func([ReportID, ReportStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };