/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CyberbullyingReport {
  'id' : ReportID,
  'status' : ReportStatus,
  'isAnonymous' : boolean,
  'description' : string,
  'timestamp' : bigint,
  'reporter' : Principal,
}
export type ReportID = bigint;
export type ReportStatus = { 'resolved' : null } |
  { 'underReview' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  'getAllReports' : ActorMethod<[], Array<CyberbullyingReport>>,
  'getReport' : ActorMethod<[ReportID], CyberbullyingReport>,
  'getReportsByStatus' : ActorMethod<
    [ReportStatus],
    Array<CyberbullyingReport>
  >,
  'submitReport' : ActorMethod<[string, boolean], ReportID>,
  'updateReportStatus' : ActorMethod<[ReportID, ReportStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];