/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ReportID = bigint;
export interface CyberbullyingReport {
    id: ReportID;
    status: ReportStatus;
    isAnonymous: boolean;
    description: string;
    timestamp: bigint;
    reporter: Principal;
}
export enum ReportStatus {
    resolved = "resolved",
    underReview = "underReview",
    rejected = "rejected"
}
export interface backendInterface {
    getAllReports(): Promise<Array<CyberbullyingReport>>;
    getReport(id: ReportID): Promise<CyberbullyingReport>;
    getReportsByStatus(status: ReportStatus): Promise<Array<CyberbullyingReport>>;
    submitReport(description: string, isAnonymous: boolean): Promise<ReportID>;
    updateReportStatus(id: ReportID, newStatus: ReportStatus): Promise<void>;
}
import type { CyberbullyingReport as _CyberbullyingReport, ReportID as _ReportID, ReportStatus as _ReportStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllReports(): Promise<Array<CyberbullyingReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReports();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReports();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(arg0: ReportID): Promise<CyberbullyingReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_CyberbullyingReport_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_CyberbullyingReport_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportsByStatus(arg0: ReportStatus): Promise<Array<CyberbullyingReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsByStatus(to_candid_ReportStatus_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsByStatus(to_candid_ReportStatus_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitReport(arg0: string, arg1: boolean): Promise<ReportID> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReport(arg0, arg1);
            return result;
        }
    }
    async updateReportStatus(arg0: ReportID, arg1: ReportStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReportStatus(arg0, to_candid_ReportStatus_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReportStatus(arg0, to_candid_ReportStatus_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CyberbullyingReport_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CyberbullyingReport): CyberbullyingReport {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReportID;
    status: _ReportStatus;
    isAnonymous: boolean;
    description: string;
    timestamp: bigint;
    reporter: Principal;
}): {
    id: ReportID;
    status: ReportStatus;
    isAnonymous: boolean;
    description: string;
    timestamp: bigint;
    reporter: Principal;
} {
    return {
        id: value.id,
        status: from_candid_ReportStatus_n4(_uploadFile, _downloadFile, value.status),
        isAnonymous: value.isAnonymous,
        description: value.description,
        timestamp: value.timestamp,
        reporter: value.reporter
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    underReview: null;
} | {
    rejected: null;
}): ReportStatus {
    return "resolved" in value ? ReportStatus.resolved : "underReview" in value ? ReportStatus.underReview : "rejected" in value ? ReportStatus.rejected : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CyberbullyingReport>): Array<CyberbullyingReport> {
    return value.map((x)=>from_candid_CyberbullyingReport_n2(_uploadFile, _downloadFile, x));
}
function to_candid_ReportStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): _ReportStatus {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): {
    resolved: null;
} | {
    underReview: null;
} | {
    rejected: null;
} {
    return value == ReportStatus.resolved ? {
        resolved: null
    } : value == ReportStatus.underReview ? {
        underReview: null
    } : value == ReportStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
